version: '3.8'
services:
  postgis:
    container_name: trips-pipeline-container
    image: "postgis/postgis:11-2.5-alpine"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always  
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trips_db
    volumes:
      - ./codes/script_by_pgmodeler.sql:/docker-entrypoint-initdb.d/script_by_pgmodeler.sql
      - ./codes:/tmp/codes
      - ./input_file:/tmp/files

    networks:
      - postgres-compose-network
  
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - trips-pipeline-container
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge